"""
RAG Retriever
=============

Retrieval tool for Xiangqi knowledge base.
Provides a unified interface for querying vector stores.

Supported Backends:
  Phase 1: In-memory mock (no dependencies)
  Phase 2: ChromaDB (embedded, zero-config)
  Phase 3: Pinecone / Weaviate (hosted, scalable)

Collections:
  - openings
  - tactics
  - endgames
  - beginner_principles

Each document has:
  - content: str         (the text)
  - metadata: dict       (topic, difficulty, piece_types, game_phase, etc.)
  - embedding: list[float]  (vector representation, generated by backend)
"""

from __future__ import annotations

import logging
from typing import Any, Optional

logger = logging.getLogger("tools.rag_retriever")

# Module-level singleton for embedding model (shared with knowledge_loader)
_embedding_model = None
_DEFAULT_MODEL_NAME = "BAAI/bge-m3"
_SIMILARITY_THRESHOLD = 0.3  # Cosine distance threshold (lower = more similar)

COLLECTION_NAMES = ["openings", "tactics", "endgames", "beginner_principles"]


def _get_embedding_model(model_name: str = _DEFAULT_MODEL_NAME):
    """Lazy-load and cache the sentence-transformer embedding model."""
    global _embedding_model
    if _embedding_model is None:
        try:
            from sentence_transformers import SentenceTransformer
            logger.info(f"Loading embedding model: {model_name} ...")
            _embedding_model = SentenceTransformer(model_name)
            logger.info("Embedding model loaded.")
        except ImportError:
            logger.error(
                "sentence-transformers not installed. "
                "Run: pip install sentence-transformers"
            )
            return None
    return _embedding_model


# ========================
#    RETRIEVER INTERFACE
# ========================

class RAGRetriever:
    """Pluggable RAG retrieval interface.

    Phase 1: Returns mock results from a built-in knowledge stub.
    Phase 2: Wraps ChromaDB for real vector similarity search.

    Usage:
        retriever = RAGRetriever(backend="mock")
        results = await retriever.retrieve("cannon tactics", collection="tactics")
    """

    def __init__(
        self,
        backend: str = "mock",
        chroma_path: Optional[str] = None,
        embedding_model: Optional[str] = None,
        similarity_threshold: Optional[float] = None,
    ):
        self._backend = backend
        self._chroma_path = chroma_path or "./chroma_db"
        self._embedding_model = embedding_model or _DEFAULT_MODEL_NAME
        self._similarity_threshold = (
            similarity_threshold if similarity_threshold is not None
            else _SIMILARITY_THRESHOLD
        )
        self._client: Any = None  # ChromaDB client or other backend

    async def initialize(self) -> bool:
        """Initialize the retriever backend.

        Returns True if backend is ready.
        """
        if self._backend == "chromadb":
            return await self._init_chromadb()
        elif self._backend == "mock":
            logger.info("RAG retriever initialized with mock backend")
            return True
        else:
            logger.warning(f"Unknown backend: {self._backend}, falling back to mock")
            self._backend = "mock"
            return True

    async def _init_chromadb(self) -> bool:
        """Initialize ChromaDB backend."""
        try:
            import chromadb
            self._client = chromadb.PersistentClient(path=self._chroma_path)
            logger.info(f"ChromaDB initialized at {self._chroma_path}")
            return True
        except ImportError:
            logger.error("chromadb not installed. Run: pip install chromadb")
            self._backend = "mock"
            return False
        except Exception as e:
            logger.error(f"ChromaDB initialization failed: {e}")
            self._backend = "mock"
            return False

    # ---- Retrieval ----

    async def retrieve(
        self,
        query: str,
        collection: str = "all",
        top_k: int = 3,
        filters: Optional[dict] = None,
    ) -> list[dict]:
        """Retrieve relevant documents for a query.

        Args:
            query: Natural language or keyword query.
            collection: Target collection name.
            top_k: Maximum number of results.
            filters: Metadata filters (e.g., {"difficulty": "beginner"}).

        Returns:
            List of dicts with "content", "score", and "metadata" keys.
        """
        if self._backend == "chromadb" and self._client:
            return await self._retrieve_chromadb(query, collection, top_k, filters)
        else:
            return self._retrieve_mock(query, collection, top_k, filters)

    def encode_query(self, text: str) -> Optional[list[float]]:
        """Encode a query string into a normalized embedding vector.

        Returns None if the embedding model is unavailable.
        """
        model = _get_embedding_model(self._embedding_model)
        if model is None:
            return None
        embedding = model.encode(text, normalize_embeddings=True)
        return embedding.tolist()

    async def _retrieve_chromadb(
        self,
        query: str,
        collection: str,
        top_k: int,
        filters: Optional[dict],
    ) -> list[dict]:
        """Retrieve from ChromaDB using vector embeddings."""
        try:
            # Support "all" collection — query each collection and merge
            collections_to_query = (
                COLLECTION_NAMES if collection == "all"
                else [collection]
            )

            query_embedding = self.encode_query(query)
            all_documents = []

            for coll_name in collections_to_query:
                try:
                    coll = self._client.get_collection(name=coll_name)
                except Exception:
                    logger.debug(f"Collection '{coll_name}' not found, skipping")
                    continue

                if coll.count() == 0:
                    continue

                where_filter = filters if filters else None

                # Use vector search if embedding available, else fall back
                if query_embedding is not None:
                    results = coll.query(
                        query_embeddings=[query_embedding],
                        n_results=min(top_k, coll.count()),
                        where=where_filter,
                    )
                else:
                    results = coll.query(
                        query_texts=[query],
                        n_results=min(top_k, coll.count()),
                        where=where_filter,
                    )

                if results and results["documents"]:
                    for i, doc in enumerate(results["documents"][0]):
                        distance = (
                            results["distances"][0][i]
                            if results.get("distances")
                            else 0.5
                        )
                        # Cosine distance: 0 = identical, 2 = opposite
                        # Convert to similarity score: 1 - distance
                        score = 1.0 - distance
                        meta = (
                            results["metadatas"][0][i]
                            if results.get("metadatas")
                            else {}
                        )
                        meta["_collection"] = coll_name
                        all_documents.append({
                            "content": doc,
                            "score": score,
                            "metadata": meta,
                        })

            # Filter by similarity threshold
            all_documents = [
                d for d in all_documents
                if d["score"] >= (1.0 - self._similarity_threshold)
            ]

            # Sort by score descending, return top_k
            all_documents.sort(key=lambda d: d["score"], reverse=True)
            return all_documents[:top_k]

        except Exception as e:
            logger.error(f"ChromaDB query failed: {e}")
            return self._retrieve_mock(query, collection, top_k, filters)

    def _retrieve_mock(
        self,
        query: str,
        collection: str,
        top_k: int,
        filters: Optional[dict],
    ) -> list[dict]:
        """Return mock documents for development/testing."""
        mock_db = {
            "openings": [
                {
                    "content": (
                        "The Central Cannon Opening (Zhong Pao) is the most common "
                        "opening in Xiangqi. Move the cannon to the center file to "
                        "control the center and threaten the opponent's central pawn."
                    ),
                    "score": 0.85,
                    "metadata": {
                        "topic": "central_cannon",
                        "difficulty": "beginner",
                    },
                },
                {
                    "content": (
                        "The Screen Horse Defense (Ping Feng Ma) is a solid "
                        "response to the Central Cannon. Both horses are developed "
                        "to defend the central pawn and control key squares."
                    ),
                    "score": 0.80,
                    "metadata": {
                        "topic": "screen_horse",
                        "difficulty": "beginner",
                    },
                },
            ],
            "tactics": [
                {
                    "content": (
                        "The Cannon's unique capture mechanic requires a 'screen' "
                        "piece between itself and the target. Setting up a double "
                        "cannon attack with a screen can create devastating threats."
                    ),
                    "score": 0.82,
                    "metadata": {
                        "topic": "cannon_tactics",
                        "difficulty": "intermediate",
                    },
                },
                {
                    "content": (
                        "The Rook is the most powerful piece in Xiangqi. "
                        "Activating your rooks early by opening files and ranks "
                        "is a fundamental tactical principle."
                    ),
                    "score": 0.78,
                    "metadata": {
                        "topic": "rook_activation",
                        "difficulty": "beginner",
                    },
                },
            ],
            "endgames": [
                {
                    "content": (
                        "In Rook vs King endgames, the winning strategy is to "
                        "use the rook to restrict the opponent's king to the edge, "
                        "then deliver checkmate with king and rook coordination."
                    ),
                    "score": 0.90,
                    "metadata": {
                        "topic": "rook_vs_king",
                        "difficulty": "beginner",
                    },
                },
            ],
            "beginner_principles": [
                {
                    "content": (
                        "In Xiangqi, each piece has specific movement rules: "
                        "the General (King) moves one step orthogonally within the "
                        "palace. Advisors move one step diagonally within the palace. "
                        "Elephants move two steps diagonally and cannot cross the river. "
                        "Horses move in an L-shape but can be blocked at the leg. "
                        "Rooks move any distance orthogonally. Cannons move like rooks "
                        "but capture by jumping over exactly one piece. Soldiers move "
                        "one step forward (and sideways after crossing the river)."
                    ),
                    "score": 0.95,
                    "metadata": {
                        "topic": "piece_movement",
                        "difficulty": "beginner",
                    },
                },
                {
                    "content": (
                        "The two Kings must never face each other on the same file "
                        "with no pieces between them. This is called the 'flying "
                        "general' rule and is unique to Xiangqi."
                    ),
                    "score": 0.88,
                    "metadata": {
                        "topic": "flying_general",
                        "difficulty": "beginner",
                    },
                },
            ],
        }

        docs = mock_db.get(collection, [])
        if not docs and collection == "all":
            docs = [d for coll in mock_db.values() for d in coll]

        # Simple keyword matching for mock relevance
        query_lower = query.lower()
        scored = []
        for doc in docs:
            content_lower = doc["content"].lower()
            keyword_hits = sum(
                1 for word in query_lower.split() if word in content_lower
            )
            adjusted_score = doc["score"] + (keyword_hits * 0.05)
            scored.append({**doc, "score": min(adjusted_score, 1.0)})

        scored.sort(key=lambda d: d["score"], reverse=True)
        return scored[:top_k]

    # ---- Collection Management ----

    async def add_documents(
        self,
        collection: str,
        documents: list[dict],
    ) -> bool:
        """Add documents to a collection (ChromaDB backend only).

        Each document dict should have:
            - "content": str
            - "metadata": dict (optional)
            - "id": str (optional, auto-generated if missing)

        Returns True on success.
        """
        if self._backend != "chromadb" or not self._client:
            logger.warning("add_documents only supported with ChromaDB backend")
            return False

        try:
            coll = self._client.get_or_create_collection(name=collection)
            ids = [
                d.get("id", f"{collection}_{i}")
                for i, d in enumerate(documents)
            ]
            contents = [d["content"] for d in documents]
            metadatas = [d.get("metadata", {}) for d in documents]

            coll.add(documents=contents, ids=ids, metadatas=metadatas)
            logger.info(
                f"Added {len(documents)} documents to '{collection}'"
            )
            return True
        except Exception as e:
            logger.error(f"Failed to add documents: {e}")
            return False

    async def list_collections(self) -> list[str]:
        """List available collection names."""
        if self._backend == "chromadb" and self._client:
            try:
                collections = self._client.list_collections()
                return [c.name for c in collections]
            except Exception as e:
                logger.error(f"Failed to list collections: {e}")
        return list(mock_db.keys()) if self._backend == "mock" else []
