#!/usr/bin/env python3
"""Build a ready-to-use reference bundle from annotated local voice clips."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def load_manifest(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def combine_style_notes(clips: list[dict[str, object]]) -> str:
    seen: list[str] = []
    for clip in clips:
        style = clip.get("style", {})
        if not isinstance(style, dict):
            continue
        for key, value in style.items():
            if not value:
                continue
            rendered = f"{key}={value}"
            if rendered not in seen:
                seen.append(rendered)
    return "; ".join(seen)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        default="tts/voice_clone_manifest.json",
        help="Path to the manifest generated by prepare_voice_cloning.py.",
    )
    parser.add_argument(
        "--voice-id",
        required=True,
        help="Voice id to bundle, e.g. chopper.",
    )
    parser.add_argument(
        "--output",
        help="Optional output path. Defaults to tts/out/<voice-id>_reference_bundle.json",
    )
    parser.add_argument(
        "--max-clips",
        type=int,
        default=3,
        help="Maximum number of ready clips to include in the bundle.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(__file__).resolve().parents[1]
    manifest_path = root / args.manifest
    manifest = load_manifest(manifest_path)
    voices = manifest.get("voices", {})
    if not isinstance(voices, dict) or args.voice_id not in voices:
        raise SystemExit(f"Voice id not found in manifest: {args.voice_id}")

    clips = voices[args.voice_id]
    if not isinstance(clips, list):
        raise SystemExit(f"Malformed manifest entry for voice id: {args.voice_id}")

    ready_clips = [clip for clip in clips if isinstance(clip, dict) and clip.get("ready")]
    if not ready_clips:
        raise SystemExit(
            f"No ready clips for {args.voice_id}. Fill in the .lab transcript files first."
        )

    selected = ready_clips[: max(args.max_clips, 1)]
    prompt_text = " ".join(str(clip["transcript"]).strip() for clip in selected).strip()
    style_summary = combine_style_notes(selected)

    output_path = root / (
        args.output or f"tts/out/{args.voice_id}_reference_bundle.json"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    bundle = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "voice_id": args.voice_id,
        "prompt_text": prompt_text,
        "style_summary": style_summary,
        "references": selected,
    }
    output_path.write_text(json.dumps(bundle, indent=2), encoding="utf-8")

    print(f"Wrote bundle: {output_path}")
    print(f"Voice id: {args.voice_id}")
    print(f"Clips included: {len(selected)}")
    print(f"Prompt text length: {len(prompt_text)}")
    if style_summary:
        print(f"Style summary: {style_summary}")
    else:
        print("Style summary: none")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
